begin;

create table if not exists public.stream_events (
  event_sequence bigint generated by default as identity primary key,
  channel character varying not null,
  event_name character varying not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists ix_stream_events_channel_sequence
  on public.stream_events(channel, event_sequence);

create index if not exists ix_stream_events_created_at
  on public.stream_events(created_at);

delete from public.stream_events
where created_at < (now() - interval '1 day');

commit;
